export type ClaudeSettingFieldType = 'string' | 'number' | 'boolean' | 'json' | 'select'

export type ClaudeSettingDefinition = {
  key: string
  label: string
  description: string
  references?: { label: string; href: string }[]
  category: string
  type: ClaudeSettingFieldType
  availability?: 'both' | 'localOnly'
  options?: string[]
  example?: unknown
}

export const CLAUDE_SETTINGS_CATALOG: ClaudeSettingDefinition[] = [
  {
    key: 'agent',
    label: 'Main agent',
    description: 'Run the main thread as a named subagent with that subagent’s prompt, tools, and model.',
    category: 'Core',
    type: 'string',
    example: 'code-reviewer',
  },
  {
    key: 'model',
    label: 'Default model',
    description: 'Override the default Claude Code model for this workspace.',
    category: 'Core',
    type: 'string',
    example: 'claude-sonnet-4-6',
  },
  {
    key: 'outputStyle',
    label: 'Output style',
    description: 'Adjust the system prompt with a named output style.',
    category: 'Core',
    type: 'string',
    example: 'Explanatory',
  },
  {
    key: 'availableModels',
    label: 'Available models',
    description: 'Restrict which models users can pick in this workspace.',
    category: 'Core',
    type: 'json',
    example: ['sonnet', 'haiku'],
  },
  {
    key: 'modelOverrides',
    label: 'Model overrides',
    description: 'Map Anthropic model IDs to provider-specific IDs such as Bedrock inference profiles.',
    category: 'Core',
    type: 'json',
    example: { 'claude-opus-4-6': 'arn:aws:bedrock:region:account:inference-profile/example' },
  },
  {
    key: 'alwaysThinkingEnabled',
    label: 'Always thinking',
    description: 'Enable extended thinking by default for all sessions.',
    category: 'Core',
    type: 'boolean',
    example: true,
  },
  {
    key: 'effortLevel',
    label: 'Effort level',
    description: 'Persist the preferred effort level across sessions.',
    category: 'Core',
    type: 'select',
    options: ['low', 'medium', 'high', 'xhigh'],
    example: 'high',
  },
  {
    key: 'awaySummaryEnabled',
    label: 'Away summary',
    description: 'Show a short recap after returning to the terminal.',
    category: 'Core',
    type: 'boolean',
    example: true,
  },
  {
    key: 'showThinkingSummaries',
    label: 'Thinking summaries',
    description: 'Show extended thinking summaries in interactive sessions.',
    category: 'Core',
    type: 'boolean',
    example: true,
  },
  {
    key: 'language',
    label: 'Response language',
    description: 'Preferred response language and voice dictation language.',
    category: 'Core',
    type: 'string',
    example: 'english',
  },
  {
    key: 'voice',
    label: 'Voice settings',
    description: 'Configure voice dictation as a structured object.',
    category: 'Core',
    type: 'json',
    example: { enabled: true, mode: 'tap' },
  },
  {
    key: 'voiceEnabled',
    label: 'Voice enabled (legacy)',
    description: 'Legacy alias for voice.enabled.',
    category: 'Core',
    type: 'boolean',
    example: true,
  },
  {
    key: 'apiKeyHelper',
    label: 'API key helper',
    description: 'Shell command used to generate auth headers dynamically.',
    category: 'Core',
    type: 'string',
    example: '/bin/generate_temp_api_key.sh',
  },
  {
    key: 'autoUpdatesChannel',
    label: 'Auto-updates channel',
    description: 'Choose whether this workspace follows stable or latest releases.',
    category: 'Session',
    type: 'select',
    options: ['latest', 'stable'],
    example: 'stable',
  },
  {
    key: 'minimumVersion',
    label: 'Minimum version',
    description: 'Prevent updates from downgrading below a specific version.',
    category: 'Session',
    type: 'string',
    example: '2.1.100',
  },
  {
    key: 'cleanupPeriodDays',
    label: 'Cleanup period (days)',
    description: 'Delete old session files after this many days.',
    category: 'Session',
    type: 'number',
    example: 20,
  },
  {
    key: 'fastModePerSessionOptIn',
    label: 'Fast mode per-session opt-in',
    description: 'Require fast mode to be enabled again each new session.',
    category: 'Session',
    type: 'boolean',
    example: true,
  },
  {
    key: 'autoMemoryDirectory',
    label: 'Auto memory directory',
    description: 'Custom storage directory for auto memory. Not read from shared project settings.',
    category: 'Session',
    type: 'string',
    availability: 'localOnly',
    example: '~/my-memory-dir',
  },
  {
    key: 'autoMode',
    label: 'Auto mode rules',
    description: 'Customize auto mode allow and soft-deny rules. Not read from shared project settings.',
    category: 'Session',
    type: 'json',
    availability: 'localOnly',
    example: { environment: ['Trusted repo: github.example.com/acme'] },
  },
  {
    key: 'useAutoModeDuringPlan',
    label: 'Use auto mode during plan',
    description: 'Enable auto mode semantics during plan mode. Not read from shared project settings.',
    category: 'Session',
    type: 'boolean',
    availability: 'localOnly',
    example: false,
  },
  {
    key: 'plansDirectory',
    label: 'Plans directory',
    description: 'Choose where Claude stores plan files relative to the project root.',
    category: 'Session',
    type: 'string',
    example: './plans',
  },
  {
    key: 'prefersReducedMotion',
    label: 'Reduced motion',
    description: 'Reduce or disable UI motion for accessibility.',
    category: 'Session',
    type: 'boolean',
    example: true,
  },
  {
    key: 'spinnerTipsEnabled',
    label: 'Spinner tips',
    description: 'Show or hide spinner tips while Claude is working.',
    category: 'Session',
    type: 'boolean',
    example: false,
  },
  {
    key: 'spinnerTipsOverride',
    label: 'Spinner tips override',
    description: 'Replace or extend the default spinner tips.',
    category: 'Session',
    type: 'json',
    example: { excludeDefault: true, tips: ['Use our internal tool X'] },
  },
  {
    key: 'spinnerVerbs',
    label: 'Spinner verbs',
    description: 'Customize verbs used in spinner and duration messages.',
    category: 'Session',
    type: 'json',
    example: { mode: 'append', verbs: ['Pondering', 'Crafting'] },
  },
  {
    key: 'tui',
    label: 'TUI renderer',
    description: 'Choose between the classic renderer and fullscreen renderer.',
    category: 'Session',
    type: 'select',
    options: ['default', 'fullscreen'],
    example: 'fullscreen',
  },
  {
    key: 'viewMode',
    label: 'View mode',
    description: 'Default transcript view mode on startup.',
    category: 'Session',
    type: 'select',
    options: ['default', 'verbose', 'focus'],
    example: 'verbose',
  },
  {
    key: 'defaultShell',
    label: 'Default shell',
    description: 'Shell used for input-box ! commands.',
    category: 'Session',
    type: 'select',
    options: ['bash', 'powershell'],
    example: 'bash',
  },
  {
    key: 'includeGitInstructions',
    label: 'Include git instructions',
    description: 'Keep Claude’s built-in git workflow guidance in the system prompt.',
    category: 'Session',
    type: 'boolean',
    example: true,
  },
  {
    key: 'respectGitignore',
    label: 'Respect .gitignore',
    description: 'Exclude ignored files from @ file suggestions.',
    category: 'Session',
    type: 'boolean',
    example: true,
  },
  {
    key: 'showClearContextOnPlanAccept',
    label: 'Show clear-context on plan accept',
    description: 'Restore the clear-context option on the plan accept screen.',
    category: 'Session',
    type: 'boolean',
    example: true,
  },
  {
    key: 'skipWebFetchPreflight',
    label: 'Skip WebFetch preflight',
    description: 'Skip Anthropic’s domain safety preflight before WebFetch.',
    category: 'Session',
    type: 'boolean',
    example: true,
  },
  {
    key: 'disableDeepLinkRegistration',
    label: 'Disable deep-link registration',
    description: 'Set to "disable" to block claude-cli:// protocol registration.',
    category: 'Session',
    type: 'select',
    options: ['disable'],
    example: 'disable',
  },
  {
    key: 'disableAutoMode',
    label: 'Disable auto mode',
    description: 'Set to "disable" to prevent auto mode from being activated.',
    category: 'Session',
    type: 'select',
    options: ['disable'],
    example: 'disable',
  },
  {
    key: 'disableSkillShellExecution',
    label: 'Disable skill shell execution',
    description: 'Block inline shell execution inside skills and custom commands.',
    category: 'Session',
    type: 'boolean',
    example: true,
  },
  {
    key: 'env',
    label: 'Environment variables',
    description: 'Environment variables applied to every session.',
    category: 'Integrations',
    type: 'json',
    example: { FOO: 'bar' },
  },
  {
    key: 'fileSuggestion',
    label: 'File suggestion command',
    description: 'Custom command used for @ file path autocomplete.',
    category: 'Integrations',
    type: 'json',
    example: { type: 'command', command: '~/.claude/file-suggestion.sh' },
  },
  {
    key: 'statusLine',
    label: 'Status line',
    description: 'Render a custom status line command in the terminal UI.',
    category: 'Integrations',
    type: 'json',
    example: { type: 'command', command: '~/.claude/statusline.sh' },
  },
  {
    key: 'hooks',
    label: 'Hooks',
    description: 'Lifecycle hooks that run custom commands or HTTP hooks.',
    category: 'Integrations',
    type: 'json',
    example: {},
  },
  {
    key: 'allowedHttpHookUrls',
    label: 'Allowed HTTP hook URLs',
    description: 'Restrict which URLs HTTP hooks may target.',
    category: 'Integrations',
    type: 'json',
    example: ['https://hooks.example.com/*', 'http://localhost:*'],
  },
  {
    key: 'httpHookAllowedEnvVars',
    label: 'HTTP hook allowed env vars',
    description: 'Restrict which environment variables HTTP hooks may interpolate.',
    category: 'Integrations',
    type: 'json',
    example: ['MY_TOKEN', 'HOOK_SECRET'],
  },
  {
    key: 'disableAllHooks',
    label: 'Disable all hooks',
    description: 'Disable hooks and custom status lines entirely.',
    category: 'Integrations',
    type: 'boolean',
    example: true,
  },
  {
    key: 'permissions',
    label: 'Permissions',
    description: 'Tool access rules, extra directories, and the default permission mode.',
    category: 'Permissions',
    type: 'json',
    example: {
      allow: ['Bash(git diff *)'],
      deny: ['Read(./.env)', 'Read(./secrets/**)'],
      defaultMode: 'acceptEdits',
    },
  },
  {
    key: 'skipDangerousModePermissionPrompt',
    label: 'Skip dangerous-mode prompt',
    description: 'Skip the bypass-permissions confirmation prompt. Ignored in shared project settings.',
    category: 'Permissions',
    type: 'boolean',
    availability: 'localOnly',
    example: true,
  },
  {
    key: 'sandbox',
    label: 'Sandbox',
    description: 'Filesystem and network sandbox configuration, including allow/deny lists.',
    category: 'Permissions',
    type: 'json',
    example: {
      enabled: true,
      autoAllowBashIfSandboxed: true,
      excludedCommands: ['docker *'],
      filesystem: {
        allowWrite: ['/tmp/build', '~/.kube'],
      },
    },
  },
  {
    key: 'enableAllProjectMcpServers',
    label: 'Enable all project MCP servers',
    description: 'Automatically approve all MCP servers declared in project .mcp.json files.',
    category: 'Integrations',
    type: 'boolean',
    example: true,
  },
  {
    key: 'enabledMcpjsonServers',
    label: 'Enabled MCP JSON servers',
    description: 'Approve specific MCP servers from .mcp.json files.',
    category: 'Integrations',
    type: 'json',
    example: ['memory', 'github'],
  },
  {
    key: 'disabledMcpjsonServers',
    label: 'Disabled MCP JSON servers',
    description: 'Reject specific MCP servers from .mcp.json files.',
    category: 'Integrations',
    type: 'json',
    example: ['filesystem'],
  },
  {
    key: 'enabledPlugins',
    label: 'Enabled plugins',
    description: 'Control which Claude plugins are enabled in this workspace.',
    category: 'Plugins',
    type: 'json',
    example: { 'formatter@team-tools': true, 'experimental@personal': false },
  },
  {
    key: 'extraKnownMarketplaces',
    label: 'Extra marketplaces',
    description: 'Declare additional plugin marketplaces for the repository.',
    category: 'Plugins',
    type: 'json',
    example: {
      'team-tools': {
        source: {
          source: 'github',
          repo: 'acme-corp/claude-plugins',
        },
      },
    },
  },
  {
    key: 'attribution',
    label: 'Git attribution',
    description: 'Customize attribution text for commits and pull requests.',
    category: 'Git',
    type: 'json',
    example: { commit: 'Generated with AI', pr: '' },
  },
  {
    key: 'companyAnnouncements',
    label: 'Company announcements',
    description: 'Announcements shown to users at startup.',
    category: 'Git',
    type: 'json',
    example: ['Welcome to Acme Corp!', 'Review our internal guidelines before coding.'],
  },
  {
    key: 'feedbackSurveyRate',
    label: 'Feedback survey rate',
    description: 'Probability from 0 to 1 that the session quality survey appears.',
    category: 'Session',
    type: 'number',
    example: 0.05,
  },
  {
    key: 'forceLoginMethod',
    label: 'Force login method',
    description: 'Restrict login to Claude.ai accounts or Console accounts.',
    category: 'Session',
    type: 'select',
    options: ['claudeai', 'console'],
    example: 'claudeai',
  },
  {
    key: 'forceLoginOrgUUID',
    label: 'Force login org UUID',
    description: 'Require login to belong to one or more organization UUIDs.',
    category: 'Session',
    type: 'json',
    example: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
  },
  {
    key: 'worktree',
    label: 'Worktree',
    description: 'Configure symlink directories and sparse checkout paths for worktrees.',
    category: 'Permissions',
    type: 'json',
    example: {
      symlinkDirectories: ['node_modules', '.cache'],
      sparsePaths: ['packages/my-app', 'shared/utils'],
    },
  },
]

export const CLAUDE_SETTINGS_MAP = Object.fromEntries(
  CLAUDE_SETTINGS_CATALOG.map(setting => [setting.key, setting] as const)
) as Record<string, ClaudeSettingDefinition>
